### ISSUE TITLE
Battery Icon Font Size Problem

### ISSUE THREAD

**Issue by edizbaha** [HorizonUnix/FixRDAR4XR11#1]
![image](https://github.com/user-attachments/assets/9fa845ed-da2a-44cc-9ab9-4cf5ee05d4d6)

Is it possible to fix battery icon font size?

**Comment by gorouflex** [comment]
> ![image](https://private-user-images.githubusercontent.com/39214723/367317897-9fa845ed-da2a-44cc-9ab9-4cf5ee05d4d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMzUyODAsIm5iZiI6MTcyNjIzNDk4MCwicGF0aCI6Ii8zOTIxNDcyMy8zNjczMTc4OTctOWZhODQ1ZWQtZGEyYS00NGNjLTlhYjktNGNmNWVlMDVkNGQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDEzNDMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlYWIwY2I5N2Q4N2JhMDYzMDcwODIzNTVhNjNmMDNmNTQyZDk4YmQ3N2I5NzcyMjFlNTZkNDk1ODY0M2IwYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FFCiPB0uwqcDfgnm_EDyKNuI0xOZUJAh21cQo3qT_hI)
> 
> Is it possible to fix battery icon font size?

No, it's Apple UI issue

**Comment by edizbaha** [comment]
Can I move the dynamic island to under the notch?

**Comment by gorouflex** [comment]
> Can I move the dynamic island to under the notch?

if someone can somehow able to use `Zg7DduDoSCy6vY6mhy3n2w` aka `island-notch-location` key in mobilegestalt so maybe you can move it down

**Comment by edizbaha** [comment]
Is it possible to apply this method? Can you do that? @gorouflex 

https://www.reddit.com/r/jailbreak/comments/1dby5tz/fixing_rdar45025538_after_enabling_dynamic_island/

**Comment by gorouflex** [comment]
> Is it possible to apply this method? Can you do that? @gorouflex 
> 
> 
> 
> https://www.reddit.com/r/jailbreak/comments/1dby5tz/fixing_rdar45025538_after_enabling_dynamic_island/

Patched since iOS 17.0

**Comment by TheLiveYT** [comment]
I just live with it 👍🏻
